#this plugin is made by maxxie114

name: ExamplePlugin
main: examplePlugin.ExamplePlugin

version: "3.0.0"
api: ["1.0.7"]
author: maxxie114

commands:
  getText:
    description: "run example plugin command"
    usage: "/getText"
  getNum:
    description: "run example plugin command"
    usage: "/getNum"
