#this plugin is made by maxxie114

name: ExamplePlugin
main: examplePlugin.ExamplePlugin

version: "3.0.0"
api: ["1.0.7"]
author: maxxie114

commands:
  gettext:
    description: "run example plugin command"
    usage: "/getText"
  getnum:
    description: "run example plugin command"
    usage: "/getNum"
  yeet:
    description: "yee haw"
    usage: "/yeet "
